name: Chrome headless

on: push

jobs:
  chrome-headless:
    runs-on: ubuntu-latest
    #container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Headless Chrome
        uses: cypress-io/github-action@v2.9.7
        timeout-minutes: 10
        with:
          browser: chrome
          headless: true
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
